package com.cts.web.sys.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompanyAreaId generated by hbm2java
 */
@Embeddable
public class RoleFunctionId implements java.io.Serializable {

	private String roleId;
	private String funcId;

	public RoleFunctionId() {
	}

	public RoleFunctionId(String roleId, String funcId) {
		this.roleId = roleId;
		this.funcId = funcId;
	}

	@Column(name = "ROLE_ID", nullable = false, length = 50)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "FUNC_ID", nullable = false, length = 50)
	public String getFuncId() {
		return this.funcId;
	}

	public void setFuncId(String funcId) {
		this.funcId = funcId;
	}

	
}