package com.cts.web.sys.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysUserRoleId generated by hbm2java
 */
@Embeddable
public class SysUserRoleId implements java.io.Serializable {

	private String userId;
	private String rolecode;

	public SysUserRoleId() {
	}

	public SysUserRoleId(String userId, String rolecode) {
		this.userId = userId;
		this.rolecode = rolecode;
	}

	@Column(name = "USER_ID", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "ROLECODE", nullable = false, length = 20)
	public String getRolecode() {
		return this.rolecode;
	}

	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}


}
